
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package analisis;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int APAGAR = 29;
  public static final int NUMERO = 57;
  public static final int PUERTAS = 24;
  public static final int ENCENDER = 30;
  public static final int POR = 17;
  public static final int CADA = 16;
  public static final int AR_MULTIPLICACION = 43;
  public static final int REL_MENOR = 35;
  public static final int SEG = 18;
  public static final int ABRIR = 21;
  public static final int ENTERO = 4;
  public static final int FUNCION = 34;
  public static final int OBTENER = 26;
  public static final int REL_MAYOR = 36;
  public static final int PARENTESIS_ABIERTO = 51;
  public static final int FIN = 2;
  public static final int LLAVE_ABIERTA = 53;
  public static final int VENTILAR = 8;
  public static final int IDENTIFICADOR = 59;
  public static final int COMIENZO = 3;
  public static final int SINO = 7;
  public static final int PERSONAS = 28;
  public static final int MANTENER = 25;
  public static final int DECLARAR = 14;
  public static final int INC = 48;
  public static final int COMO = 15;
  public static final int OP_BOOLEANO = 58;
  public static final int LOGICO_AND = 46;
  public static final int MIN = 19;
  public static final int PUNTO_COMA = 55;
  public static final int CONDICION = 6;
  public static final int AR_RESTA = 42;
  public static final int SALIR = 12;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int COMA = 56;
  public static final int NEGACION = 45;
  public static final int LOGICO = 5;
  public static final int DISPENSAR = 11;
  public static final int HR = 20;
  public static final int ASIGNACION = 50;
  public static final int REL_MAYOR_IGUAL = 38;
  public static final int ADMITIR = 9;
  public static final int VENTANAS = 23;
  public static final int REL_DIFERENTE = 39;
  public static final int CERRAR = 22;
  public static final int AR_DIVISION = 44;
  public static final int ESTADO = 33;
  public static final int SANITIZAR = 31;
  public static final int REL_MENOR_IGUAL = 37;
  public static final int PARENTESIS_CERRADO = 52;
  public static final int LOGICO_OR = 47;
  public static final int REL_IGUAL = 40;
  public static final int LLAVE_CERRADA = 54;
  public static final int AR_SUMA = 41;
  public static final int INICIO = 13;
  public static final int DEC = 49;
  public static final int LUCES = 32;
  public static final int AULAVACIA = 10;
  public static final int TEMPERATURA = 27;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "FIN",
  "COMIENZO",
  "ENTERO",
  "LOGICO",
  "CONDICION",
  "SINO",
  "VENTILAR",
  "ADMITIR",
  "AULAVACIA",
  "DISPENSAR",
  "SALIR",
  "INICIO",
  "DECLARAR",
  "COMO",
  "CADA",
  "POR",
  "SEG",
  "MIN",
  "HR",
  "ABRIR",
  "CERRAR",
  "VENTANAS",
  "PUERTAS",
  "MANTENER",
  "OBTENER",
  "TEMPERATURA",
  "PERSONAS",
  "APAGAR",
  "ENCENDER",
  "SANITIZAR",
  "LUCES",
  "ESTADO",
  "FUNCION",
  "REL_MENOR",
  "REL_MAYOR",
  "REL_MENOR_IGUAL",
  "REL_MAYOR_IGUAL",
  "REL_DIFERENTE",
  "REL_IGUAL",
  "AR_SUMA",
  "AR_RESTA",
  "AR_MULTIPLICACION",
  "AR_DIVISION",
  "NEGACION",
  "LOGICO_AND",
  "LOGICO_OR",
  "INC",
  "DEC",
  "ASIGNACION",
  "PARENTESIS_ABIERTO",
  "PARENTESIS_CERRADO",
  "LLAVE_ABIERTA",
  "LLAVE_CERRADA",
  "PUNTO_COMA",
  "COMA",
  "NUMERO",
  "OP_BOOLEANO",
  "IDENTIFICADOR"
  };
}

